<?php

namespace Database\seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class ProgramKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        //data proker deputi 1 asdep 1

        \DB::table('program_kerja')->insert(
            ['id_proker' => 1,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2021-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 2,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 3,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 4,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 5,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 6,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2021-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 7,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 8,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 9,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 10,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
            
        \DB::table('program_kerja')->insert(
            ['id_proker' => 11,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 12,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 13,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 14,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 15,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
     
        \DB::table('program_kerja')->insert(
            ['id_proker' => 16,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2021-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 17,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 18,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 19,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 20,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 21,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 22,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 23,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 24,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 25,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 1', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
                
    //---------------------End Of Deputi 1 Asdep 1 Proker

    //Data Proker Deputi 1 Asdep 2

        \DB::table('program_kerja')->insert(
            ['id_proker' => 26,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 27,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 28,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 29,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 30,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        

        \DB::table('program_kerja')->insert(
            ['id_proker' => 31,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 32,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 33,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 34,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 35,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
            
        \DB::table('program_kerja')->insert(
            ['id_proker' => 36,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 37,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 38,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
           
        \DB::table('program_kerja')->insert(
            ['id_proker' => 39,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);     
                
        \DB::table('program_kerja')->insert(
            ['id_proker' => 40,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 41,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 2', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);

        //End of Proker Deputi 1 Asdep 2

        //data proker for Deputi 1 Asdep 3


        \DB::table('program_kerja')->insert(
            ['id_proker' => 42,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2021-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 43,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 44,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 45,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 46,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 47,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2021-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 48,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 49,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 50,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 51,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
            
        \DB::table('program_kerja')->insert(
            ['id_proker' => 52,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 53,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 54,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 55,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 56,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
     
        \DB::table('program_kerja')->insert(
            ['id_proker' => 57,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2021-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 58,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 59,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 60,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 61,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 62,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 63,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 64,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 65,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 66,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 3', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        
        //end of data proker for deputi 1 asdep 3        
        

        //Data Proker for Deputi 1 Asdep 4

        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 67,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 68,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 69,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 70,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 71,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 72,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 73,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 74,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 75,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 76,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 77,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 78,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 4', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);
        
        //end of data proker for deputi 1 asdep 4

        //Data proker for deputi 1 Asdep 5

        \DB::table('program_kerja')->insert(
            ['id_proker' => 79,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 5', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2025-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 80,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 5', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 81,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 82,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 5', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 83,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 5', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 84,
             'id_unitkerja' => '001',
             'deputi' => 'Deputi 1', 'asdep' => 'Asdep 5', 
             'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
             'substansi'=>'Kesehatan', 
             'pic_proker'=>'Naomi', 
             'kolaborator'=>'', 
             'tgl_mulai'=> '2021-05-05', 
             'tgl_akhir'=>'2022-01-18', 
             'kategori'=>'Arahan Mentri',
             'status'=>'Active',
             'progres'=>'40%',
             'kendala'=>'',
             'tindak_lanjut'=>'',
             'keterangan'=>'']);


            \DB::table('program_kerja')->insert(
            ['id_proker' => 85,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 86,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 87,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
            
        \DB::table('program_kerja')->insert(
            ['id_proker' => 88,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Asdep 5', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 89,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 90,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
            
        \DB::table('program_kerja')->insert(
            ['id_proker' => 91,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);     
                
        \DB::table('program_kerja')->insert(
            ['id_proker' => 92,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 93,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 94,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 95,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 96,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 97,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 98,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 99,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 100,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Asdep 5', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);
        
        //end of data proker for deputi 1 asdep 5

        //Data proker for deputi 1 Sekdep

        \DB::table('program_kerja')->insert(
            ['id_proker' => 101,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Sekdep', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 102,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Sekdep', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 103,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Sekdep', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 104,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Sekdep', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 105,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Sekdep', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 106,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Sekdep', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);


        \DB::table('program_kerja')->insert(
            ['id_proker' => 107,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Sekdep', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
    
        \DB::table('program_kerja')->insert(
            ['id_proker' => 108,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Sekdep', 
            'nama_proker'=>'Pembangunan Wilayah Pemukiman Untuk Daerah Terkena Bencana Alam', 
            'substansi'=>'Pembangunan Pemukiman', 
            'pic_proker'=>'Cindy', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-09-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Suspended',
            'progres'=>'50%',
            'kendala'=>'Alat Trasnportasi yang Tidak Memadai',
            'tindak_lanjut'=>'Menyediakan transportasi yang memadai untuk tim',
            'keterangan'=>'Alat transportasi akan disesuaikan dengan jumlah bawaan oleh tim']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 109,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Sekdep', 
            'nama_proker'=>'Penyebaran Vaksin di Daerah Jawa Barat', 
            'substansi'=>'Penyebaran Vaksin', 
            'pic_proker'=>'Erika', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Overdue',
            'progres'=>'80%',
            'kendala'=>'Kurangnya jumlah orang untuk melakukan penyebaran vaksin',
            'tindak_lanjut'=>'Akan dialihkan ke unit kerja lainnya',
            'keterangan'=>'Unit kerja yang ada sekarang jumlah nya kurang memadai sehingga akan dialihkan ke unit kerja lainnya']);
            
        \DB::table('program_kerja')->insert(
            ['id_proker' => 110,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep' => 'Sekdep', 
            'nama_proker'=>'Permasalahan Kesehatan di Jakarta', 
            'substansi'=>'Kesehatan', 
            'pic_proker'=>'Naomi', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-05-05', 
            'tgl_akhir'=>'2022-01-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Active',
            'progres'=>'40%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
        
        \DB::table('program_kerja')->insert(
            ['id_proker' => 111,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Sekdep', 
            'nama_proker'=>'Pembangunan Bendungan di Nganjuk', 
            'substansi'=>'Pembangungan Bendungan', 
            'pic_proker'=>'Roy', 
            'kolaborator'=>'Deputi 2', 
            'tgl_mulai'=> '2021-08-17', 
            'tgl_akhir'=>'2022-10-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Pending',
            'progres'=>'20%',
            'kendala'=>'Libur Lebaran',
            'tindak_lanjut'=>'Akan dilanjutkan setelah lebaran selesai',
            'keterangan'=>'Para pekerja sedang diliburkan']);

        \DB::table('program_kerja')->insert(
            ['id_proker' => 112,
            'id_unitkerja' => '001',
            'deputi' => 'Deputi 1', 'asdep'=>'Sekdep', 
            'nama_proker'=>'Distribusi Buku Pelajaran ke Daerah Terpencil', 
            'substansi'=>'Distribusi Buku', 
            'pic_proker'=>'Yohanes', 
            'kolaborator'=>'', 
            'tgl_mulai'=> '2021-04-05', 
            'tgl_akhir'=>'2021-06-18', 
            'kategori'=>'Arahan Mentri',
            'status'=>'Done',
            'progres'=>'100%',
            'kendala'=>'',
            'tindak_lanjut'=>'',
            'keterangan'=>'']);
            
        
    }

}
